// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2EEBO2ha0pIL8GSIAzaIzag4h7QsPrdA',
    appId: '1:345249225162:web:6a0e411726e9efaa67d733',
    messagingSenderId: '345249225162',
    projectId: 'pandahub-7329d',
    authDomain: 'pandahub-7329d.firebaseapp.com',
    storageBucket: 'pandahub-7329d.appspot.com',
    measurementId: 'G-7DZPN2TZJJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gtdbSPulYB9Sn7Pm57nENUr_ai1XQ4s',
    appId: '1:345249225162:ios:769017e679cc68ee67d733',
    messagingSenderId: '345249225162',
    projectId: 'pandahub-7329d',
    storageBucket: 'pandahub-7329d.appspot.com',
    iosBundleId: 'com.example.pandahubfrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6gtdbSPulYB9Sn7Pm57nENUr_ai1XQ4s',
    appId: '1:345249225162:ios:769017e679cc68ee67d733',
    messagingSenderId: '345249225162',
    projectId: 'pandahub-7329d',
    storageBucket: 'pandahub-7329d.appspot.com',
    iosBundleId: 'com.example.pandahubfrontend',
  );
}
